### ISSUE TITLE
bug при добавлении Lombok в IntelliJ IDEA

### ISSUE THREAD

**Issue by ArtemLy7** [ArtemLy7/dont-work#1]
1. Курс "Автоматизированное тестирование"
Занятие "Основы автоматизации"
2. Задача: просмотрев видео Lombok & Lambda добавить инструмент Lombok в файл build.gradle на IntelliJ IDEA
3. Шаги:
3.1 Открываем IntelliJ IDEA 
3.2 Создаем новый проект Gradle используя библиотеку Java
3.3 В созданном проекте открываем файл build.gradle
![2019-10-18_1258_1](https://user-images.githubusercontent.com/56083531/67085539-aa451f80-f1a7-11e9-87e6-c9fe35d5f1cd.png)
3.4 Заходим на сайт https://docs.freefair.io/gradle-plugins/4.1.2/reference/
3.5 В пункте 2. Installation копируем строчку `id "io.freefair.lombok" version "4.1.2"`
3.6 Возвращаемся в IntelliJ IDEA -> файл build.gradle -> вставляем скопированную строчку в plugins и нажимаем import changes
![2019-10-18_1319!](https://user-images.githubusercontent.com/56083531/67086780-33f5ec80-f1aa-11e9-9d34-6d7b8354e120.png)

4. **Ожидаемый результат: импорт изменений проходит успешно, без ошибок**
5. **Фактический результат: появляется ошибка**
```
Unable to load class 'org.gradle.api.provider.MapProperty'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```
![2019-10-18_1328](https://user-images.githubusercontent.com/56083531/67087211-212fe780-f1ab-11e9-83ec-da0cfad2e9ba.png)
6. Тестовое окружение:
 ОС Windows 7 домашняя расширенная Service Pack 1 64x разрядная система
 Версия Java 1.8.0_212
 Версия IntelliJ IDEA community 2019.1

**Comment by coursar** [comment]
Решение:
1. Обновиться до последней версии IDEA (2019.2)
2. В текущем проекте вручную в файле `gradle/wrapper/gradle-wrapper.properties` прописать:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.2.1-all.zip
```
3. После чего сделать реимпорт

У вас прописана версия 4.
